server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123888
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

#日志打印配置  --新添加的，demo里面没有
#logging:
#  level:
#    com.example.demo.dao: debug
#logging:
#  config: classpath:log4j2.properties
